set number
set nocompatible
filetype indent plugin on
set tags=.ctags
set hidden
set wildmenu
set showcmd
set hlsearch
set ignorecase
set smartcase
set backspace=indent,eol,start
set autoindent
set nostartofline
set ruler
set confirm
set visualbell
set t_vb=
set mouse=a
set notimeout ttimeout ttimeoutlen=200
set ts=2 sw=2 expandtab
syntax on
filetype on
