---
- name: install packages
  apt: name={{item}} state=installed update_cache=yes
  with_items:
    - ntp
    - atop
    - docker.io
    - libboost-program-options1.58.0
    - libboost-system1.58.0
    - libboost-thread1.58.0
    - etcd
    - byobu
  tags: packages

- name: pi names in hosts
  lineinfile: dest=/etc/hosts line={{item}}
  with_items:
    - 192.168.0.1 pi1
    - 192.168.0.2 pi2
    - 192.168.0.3 pi3
    - 192.168.0.4 pi4
    - 192.168.0.5 pi5
  tags: hosts

- name: copy sudoers file
  copy: src=sudoers dest=/etc/sudoers force=yes mode=0440
  tags: sudoers

- name: remove swap file
  lineinfile: dest=/etc/fstab state=absent line='/var/swap none swap sw 0 0'
  register: swap_fstab

- name: disable swap
  shell: swapoff -a
  when: swap_fstab.changed

- name: rm swap
  file: dest=/var/swap state=absent force=yes
  when: swap_fstab.changed

- name: copy vimrc
  copy: src=vimrc dest=/home/rusik/.vimrc

- name: copy docker defaults
  copy: src=docker dest=/etc/default/docker
  register: docker_file

- name: restart docker on defaults file change
  service: name=docker state=restarted
  when: docker_file.changed
