---
- name: install packages
  apt: name={{item}} state=installed update_cache=yes
  with_items:
    - nload
    - ntp
    - atop
    - lxc
    - linux-tools-generic
    - lsb-release
    - gdb
    - cpuburn
    - build-essential
    - clang
    - distcc
    - distcc-pump
    - libboost-all-dev
    - git
    - cmake

- name: pi names in hosts
  lineinfile: dest=/etc/hosts line={{item}}
  with_items:
    - 192.168.0.1 pi1
    - 192.168.0.2 pi2
    - 192.168.0.3 pi3
    - 192.168.0.4 pi4
    - 192.168.0.5 pi5

- name: copy sudoers file
  copy: src=sudoers dest=/etc/sudoers force=yes mode=0440

- name: copy burn.sh
  copy: src=burn.sh dest=/usr/local/bin/burn.sh mode=755 owner=root

- name: copy temp.sh
  copy: src=temp.sh dest=/usr/local/bin/temp.sh mode=755 owner=root

- name: copy distcc hosts file
  copy: src=distcc_hosts dest=/etc/distcc/hosts
  register: distcc_hosts

- name: copy distcc default file
  template: src=distcc_default dest=/etc/default/distcc
  register: distcc_default

- name: restart distcc on hosts or default change
  service: name=distcc state=restarted
  when: distcc_hosts.changed or distcc_default.changed

- name: ensure distcc is started and enabled
  service: name=distcc state=started enabled=yes

- name: dist-upgrade
  apt: update_cache=yes upgrade=dist


