---
- name: install packages
  apt: name={{item}} state=installed update_cache=yes
  with_items:
      - clang
      - cmake
      - openvpn
      - gdb
      - lldb
      - build-essential
      - ipython
      - python3
      - ipython3
      - python3-pip
      - python-pip
      - python-dev
      - python3-dev
      - libncurses5-dev
      - mc
      - git
      - devscripts
      - dh-make
      - telnet
      - libboost-all-dev
      - yamllint
      - valgrind
      - tcpdump
      - clang-format
