---
- name: install packages
  apt: name={{item}} state=installed update_cache=yes
  with_items:
      - clang
      - cmake
      - openvpn
      - gdb
      - lldb
      - ipython
      - python3
      - ipython3
      - python3-pip
      - python-pip
      - python-dev
      - python3-dev
      - libncurses5-dev
      - libboost-dev
      - libboost-system-dev
      - libboost-thread-dev
      - libboost-program-options-dev
      - mc
      - devscripts
      - dh-make
      - telnet
      - yamllint
      - valgrind
      - tcpdump
      - clang-format
      - libgtest-dev
      - iptables-persistent
      - libc++-dev
      - libstdc++6-5-dbg-armhf-cross

- name: enable ip_forward
  lineinfile: dest=/etc/sysctl.conf state=present line='net.ipv4.ip_forward = 1'
  register: sysctl_conf

- name: sysctl -p
  shell: sysctl -p
  when: sysctl_conf.changed

- name: enable masquerade
  shell: iptables -t nat -A POSTROUTING -o enxdc9b9cee12cf -j MASQUERADE

